import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import BellIcon from "../components/bell";
import store from "../redux/store";
import storeBasic from "../redux/storebasic";
import { Provider } from "react-redux";
import Addnoti from "../components/AddNoti";
import Removenoti from "../components/readNoti";
import Addnotibasic from "../components/Addnotibasic";
import Removenotibasic from "../components/readNotibasic";
import Bellbasic from "../components/bellbasic";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Redux Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.main}>
        <Provider store={store}>
          <BellIcon />

          <h1 className={styles.title}>
            Welcome to <a href="#">Next.js!</a>
          </h1>
          <div className={styles.grid}>
            <Addnoti />
            <Removenoti />
          </div>
        </Provider>

        <Provider store={storeBasic}>
          <Bellbasic />
          <div className={styles.grid}>
            <Addnotibasic />
            <Removenotibasic />
          </div>
        </Provider>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
